### ISSUE TITLE
Docker build валится при установке ruby

### ISSUE THREAD

**Issue by volodkindv** [crsde/one-ws#2]
https://github.com/crsde/one-ws/blob/8f954c8d477b79752f023c54307979dd3232a1b9/Dockerfile#L23

В моем случае установщик обработал такой перенос строки как новую команду. Т.е. вместо "sudo apt-get install -y ..... ruby ..." он попытался выполнить 2 команды:
"sudo apt-get install -y ..... "
"ruby ..."
Исправил у себя, заработало.

**Comment by al-prk** [comment]
Не удалось у себя воспроизвести, но поправил, спасибо
https://github.com/crsde/one-ws/commit/c1ff0ed2e7bea1a776f72052b9e919fd5b3fdcd7
